### ISSUE TITLE
When I copy and paste the key using ploi token, the command doesn't allow the full key

### ISSUE THREAD

**Issue by richardfrankza** [schmidfelix/ploi-cli#6]
When I copy and paste the key using ploi token, the command doesn't allow the full key to be pasted. I'm not sure if the key length has changed or it's just some terminal setting I have incorrect.

**Comment by schmidfelix** [comment]
I can't reproduce that on my machine. What OS are you using and which Terminal? Does the command give you an error, or can't you just paste the complete token? Maybe try wrapping it in quotes?

**Comment by richardfrankza** [comment]
Hi there

I ran `ploi token` and was prompted for a key. The terminal couldn't take the large input in the prompt.

If you run `ploi token "xyz"` it works, so I'm now on my way.

**Comment by richardfrankza** [comment]
Sorry just to add I was in Mac OSX terminal and iterm2.

**Comment by SamuelNitsche** [comment]
Same thing here on Mac and iTerm 2

**Comment by sinnbeck** [comment]
That should be easy to test. Create a new command in a laravel project, with ask and see how many characters it will take

```
$test  = $this->ask('Test');
```
But my guess is that it is just a limit that ploi-cli cannot change.. Maybe a warning should be added to explain how to work around it?

**Comment by schmidfelix** [comment]
That indeed seems to be the problem. For now I've just made the command argument required, so you have to pass the token to the command as this does not seems to make any problems.

**Comment by SamuelNitsche** [comment]
I think this is a valid fix for now but this isn't ideal yet. This way, the ploi token is visible in the command line history.

**Comment by sinnbeck** [comment]
Maybe someone could test if it works with `->secret()` instead of `->ask()`?
