### ISSUE TITLE
Use Ploi's Staging -> Deploy to Production feature

### ISSUE THREAD

**Issue by chasegiunta** [schmidfelix/ploi-cli#7]
Looks like the deploy command triggers the site's deploy script configured, but Ploi has a "Deploy to production" feature when staging sites are set up. Init ploi CLI with either the staging site or the production site, doesn't run the correct "Deploy to production" script.

![image](https://user-images.githubusercontent.com/1377169/128606757-b338ee0b-44b0-4ed0-9f71-1e2261910475.png)

When staging sites are set up, the deployment script for production sites behaves a bit differently:
![image](https://user-images.githubusercontent.com/1377169/128606791-d45d336c-77b1-4110-bdca-a64cf78cf6a5.png)

So, attempting to _deploy the production site_, doesn't work.

Do you think it would be possible to add support for this? Thanks for the work you've done on this so far!

**Comment by schmidfelix** [comment]
Hey,

thanks for the detailed issue! I'm going to take a look at this later this week, but I'm sure this is something which can be added easily.

**Comment by schmidfelix** [comment]
This is added in the next release, you can easily update the cli via `composer global update schmidfelix/ploi-cli`

**Comment by chasegiunta** [comment]
@schmidfelix just FYI, I haven't been able to get this to successfully work. It gives me the message `Deploying staging site to production...` but nothing seems to actually happen. I've had to go into Ploi's GUI and deploy that way.

**Comment by sinnbeck** [comment]
That sounds a bit like an issue with ploi, and not the cli tool. It calls the url just as specified in the docs

https://github.com/schmidfelix/ploi-cli/blob/52a60428b3c85255c1bb000f5485d3e037db7ae7/app/Support/Ploi.php#L107

https://developers.ploi.io/deployments/deploy-staging-site-to-production

**Comment by schmidfelix** [comment]
As @sinnbeck said, that shouldn't be a problem with the CLI tool. But you have to make sure, that the site id specified in your `ploi.yml` config file must be the id of the staging site.

**Comment by chasegiunta** [comment]
@schmidfelix !! gotcha. that makes sense. I changed it over to the staging site ID and all works. thanks!
